-- Run in Supabase SQL Editor
create extension if not exists "pgcrypto";

create table if not exists news (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  summary text not null,
  content text not null,
  image text not null,
  date date not null default current_date
);

create table if not exists matches (
  id uuid primary key default gen_random_uuid(),
  team_home text not null,
  team_away text not null,
  category text not null,
  date date not null,
  time text not null,
  location text not null,
  badge_home text,
  badge_away text
);

create table if not exists sponsors (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  logo text not null,
  type text not null check (type in ('patrocinador', 'apoiador', 'parceiro'))
);

create table if not exists products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  price numeric(10,2) not null,
  image text not null,
  category text not null
);

create table if not exists site_settings (
  id bigint primary key generated by default as identity,
  hero_title text not null,
  hero_subtitle text not null,
  hero_image text,
  phone text not null,
  email text not null,
  address text not null
);

alter table news enable row level security;
alter table matches enable row level security;
alter table sponsors enable row level security;
alter table products enable row level security;
alter table site_settings enable row level security;

-- Public read access for site rendering
drop policy if exists "public read news" on news;
create policy "public read news" on news for select using (true);

drop policy if exists "public read matches" on matches;
create policy "public read matches" on matches for select using (true);

drop policy if exists "public read sponsors" on sponsors;
create policy "public read sponsors" on sponsors for select using (true);

drop policy if exists "public read products" on products;
create policy "public read products" on products for select using (true);

drop policy if exists "public read site_settings" on site_settings;
create policy "public read site_settings" on site_settings for select using (true);

-- Admin write access (email must match your admin account)
drop policy if exists "admin write news" on news;
create policy "admin write news" on news
for all
using (auth.role() = 'authenticated' and auth.email() = 'galomaringatv@gmail.com')
with check (auth.role() = 'authenticated' and auth.email() = 'galomaringatv@gmail.com');

drop policy if exists "admin write matches" on matches;
create policy "admin write matches" on matches
for all
using (auth.role() = 'authenticated' and auth.email() = 'galomaringatv@gmail.com')
with check (auth.role() = 'authenticated' and auth.email() = 'galomaringatv@gmail.com');

drop policy if exists "admin write sponsors" on sponsors;
create policy "admin write sponsors" on sponsors
for all
using (auth.role() = 'authenticated' and auth.email() = 'galomaringatv@gmail.com')
with check (auth.role() = 'authenticated' and auth.email() = 'galomaringatv@gmail.com');

drop policy if exists "admin write products" on products;
create policy "admin write products" on products
for all
using (auth.role() = 'authenticated' and auth.email() = 'galomaringatv@gmail.com')
with check (auth.role() = 'authenticated' and auth.email() = 'galomaringatv@gmail.com');

drop policy if exists "admin write site_settings" on site_settings;
create policy "admin write site_settings" on site_settings
for all
using (auth.role() = 'authenticated' and auth.email() = 'galomaringatv@gmail.com')
with check (auth.role() = 'authenticated' and auth.email() = 'galomaringatv@gmail.com');

insert into site_settings (id, hero_title, hero_subtitle, hero_image, phone, email, address)
values (
  1,
  'A FORCA DO GALO E A PAIXAO DA TORCIDA',
  'Unidos pela mesma paixao. Acompanhe o Galo Maringa FC na luta por grandes conquistas no futebol paranaense e brasileiro.',
  '/images/hero-banner.jpg',
  '(44) 3000-0000',
  'contato@galomaringa.com.br',
  'Estadio Willie Davids, Maringa, Parana - Brasil'
)
on conflict (id) do update set
  hero_title = excluded.hero_title,
  hero_subtitle = excluded.hero_subtitle,
  hero_image = excluded.hero_image,
  phone = excluded.phone,
  email = excluded.email,
  address = excluded.address;

insert into storage.buckets (id, name, public)
values ('site-assets', 'site-assets', true)
on conflict (id) do nothing;

drop policy if exists "Public read site assets" on storage.objects;
create policy "Public read site assets"
on storage.objects for select
using (bucket_id = 'site-assets');

drop policy if exists "Admin insert site assets by folder" on storage.objects;
create policy "Admin insert site assets by folder"
on storage.objects for insert
with check (
  bucket_id = 'site-assets'
  and auth.role() = 'authenticated'
  and auth.email() = 'galomaringatv@gmail.com'
  and (
    name like 'hero/%'
    or name like 'news/%'
    or name like 'products/%'
    or name like 'sponsors/%'
    or name like 'matches/%'
  )
);

drop policy if exists "Admin update site assets by folder" on storage.objects;
create policy "Admin update site assets by folder"
on storage.objects for update
using (
  bucket_id = 'site-assets'
  and auth.role() = 'authenticated'
  and auth.email() = 'galomaringatv@gmail.com'
  and (
    name like 'hero/%'
    or name like 'news/%'
    or name like 'products/%'
    or name like 'sponsors/%'
    or name like 'matches/%'
  )
)
with check (
  bucket_id = 'site-assets'
  and auth.role() = 'authenticated'
  and auth.email() = 'galomaringatv@gmail.com'
  and (
    name like 'hero/%'
    or name like 'news/%'
    or name like 'products/%'
    or name like 'sponsors/%'
    or name like 'matches/%'
  )
);

drop policy if exists "Admin delete site assets by folder" on storage.objects;
create policy "Admin delete site assets by folder"
on storage.objects for delete
using (
  bucket_id = 'site-assets'
  and auth.role() = 'authenticated'
  and auth.email() = 'galomaringatv@gmail.com'
  and (
    name like 'hero/%'
    or name like 'news/%'
    or name like 'products/%'
    or name like 'sponsors/%'
    or name like 'matches/%'
  )
);
